### ISSUE TITLE
ireceptor-dataloading container keeps restarting; no error in log

### ISSUE THREAD

**Issue by dtenenba** [sfu-ireceptor/turnkey-service-php#17]
Hello,

I am running ireceptor using docker-compose. It works fine for me on my local machine, but when I try and deploy it in our deployment environment, the ireceptor-dataloading keeps stopping with some sort of error, and restarting. However, looking in the container log I do not see any errors, the log ends with:

```
2021-04-21T20:16:31.024+0000 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-04-21T20:16:31.025+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
```

Any tips to help troubleshoot this?

Thanks in advance.

**Comment by bcorrie** [comment]
Hi @dtenenba, 

Can you let me know which of the docker containers is running and causing this problem. If you do a `sudo docker ps`, is it the:

`ireceptor/dataloading-mongo:turnkey-v3-performance`

container that is doing this? This container should stay up and running. My docker ps on my test VM looks like this:

```
947d9a3112d2        ireceptor/service-php-mongodb:stats-api-turnkey      "docker-php-entrypoi…"   3 weeks ago         Up 12 days          0.0.0.0:80->80/tcp   turnkey-service_ireceptor-api_1
0088a4ab554f        ireceptor/repository-mongodb:turnkey-v3              "docker-entrypoint.s…"   3 weeks ago         Up 12 days          27017/tcp            turnkey-service_ireceptor-database_1
c2a17d6114ec        ireceptor/dataloading-mongo:turnkey-v3-performance   "docker-entrypoint.s…"   5 weeks ago         Up 12 days          27017/tcp            turnkey-service_ireceptor-performance-testing_1
```
As you can see the ireceptor/dataloading-mongo:turnkey-v3-performance` docker container has been up for 12 days

**Comment by dtenenba** [comment]
It is the ireceptor-dataloading  container. 
It is actually running, and staying up, according to `docker ps`. However, our deployment system (the outdated Rancher 1, soon to be updated to something else) keeps reporting that the container is stopping and restarting.
I have not seen that behavior before.

**Comment by bcorrie** [comment]
The `ireceptor-dataloading` container (as per the docker-compose.yaml file) should not be running constantly. This container only runs when it is used to load data. The container is started when you run load_metadata.sh or load_rearrangements.sh.

In my docker ps above,  `ireceptor-dataloading` is not running. the `ireceptor-performance-testing` container, which is actually built from the ireceptor-dataloading github repository (slightly confusing I know) is always running.

If you have a deployment system that is looking for `ireceptor-dataloading` container to be running all the time, it will not find it. If it tries to start it with the `start_turnkey.sh` command, it will start and then immediately exit. Is that what you are seeing?

**Comment by dtenenba** [comment]
OK, I guess that is the problem, the deployment system expects the container to stay up and will keep trying to restart it. I will have to see if there is a way to turn off that behavior.
Unfortunately in this system I cannot bring up the app with any scripts, I can only use the docker-compose.yml file directly.

I was thrown off by the mention of "dataloading" in the output of "docker ps".

**Comment by dtenenba** [comment]
Can I just comment out that service from the docker-compose.yml? It doesn't actually need to run and exit at the same time as the other services, right? If I do need to load data I can either uncomment the service first or just start it with "docker run" instead of "docker compose run".

**Comment by bcorrie** [comment]
That should be OK, although I will ping our docker expert @jeromejaglale to add any further thoughts on this.

Our scripts (e.g. load_metadata.sh) use docker_compose to run commands within the containers, so you would need to uncomment the service when you load data. But commenting it out should be OK. The other problem you might run in to if commented out would be if/when you do an update_turnkey.sh, which updates all of the containers based on what is in the docker_compose file.

**Comment by bcorrie** [comment]
> I was thrown off by the mention of "dataloading" in the output of "docker ps".

Yeah, sorry about that - it is a bit confusing...

**Comment by dtenenba** [comment]
Looks like one can set the restart policy on a service/container in docker-compose.yml. 
http://progressivecoder.com/docker-compose-restart-policies-to-manage-docker-containers/
Can I suggest you do set the restart policy to "no"  for the dataloading container? 

Unfortunately Rancher 1 only supports docker-compose version 2, nothing higher, and I think that feature requires version 3, so I am still out of luck. I will have to spin up a separate VM to host this. Or, I could just ignore the errors if the app is otherwise running ok. But I may have problems when I actually do want to load data. 

Thanks for your help.

**Comment by bcorrie** [comment]
> Looks like one can set the restart policy on a service/container in docker-compose.yml.
> http://progressivecoder.com/docker-compose-restart-policies-to-manage-docker-containers/
> Can I suggest you do set the restart policy to "no" for the dataloading container?

Thanks we will look into that...

**Comment by dtenenba** [comment]
Unfortunately even though Rancher makes use of docker-compose.yml files, the actual docker-compose command is not used (yes, it's confusing). I guess it is using Cattle for the orchestration? I'll have to do some testing and see if I can add data to the app as it's currently set up. Actually, I have still not gotten the web app (API) to come up yet. So I will probably end up moving this to its own VM.

**Comment by bcorrie** [comment]
> Unfortunately Rancher 1 only supports docker-compose version 2, nothing higher, and I think that feature requires version 3, so I am still out of luck. I will have to spin up a separate VM to host this. Or, I could just ignore the errors if the app is otherwise running ok. But I may have problems when I actually do want to load data.

The only services required to run the service minimally are the `ireceptor-database` and `ireceptor-api` containers. The performance monitoring container is not required. To load data you would need to be able to run the `ireceptor-dataloading` container using the shell scripts and docker compose. The `ireceptor-performance-testing` is for tuning purposes and could be commented out if you don't want to use it.

**Comment by bcorrie** [comment]
Happy to help, don't hesitate to ask questions!

**Comment by bcorrie** [comment]
@dtenenba following up on this issue - did you have any luck? If there is no further discussion on this, I will close off this issue...

**Comment by dtenenba** [comment]
Thanks @bcorrie , things seem to be working OK now.
