### ISSUE TITLE
Error Loading test data

### ISSUE THREAD

**Issue by Hgracia** [sfu-ireceptor/turnkey-service-php#31]
When I execute the next command:
scripts/load_metadata.sh ireceptor test_data/PRJNA330606_Wang_1_sample_metadata.csv

I have this error:
Warning: column without a title detected in file  /scratch/PRJNA330606_Wang_1_sample_metadata.csv
ERROR: Could not find curation field study_contact in file /scratch/PRJNA330606_Wang_1_sample_metadata.csv
ERROR: iReceptor Repertoire file /scratch/PRJNA330606_Wang_1_sample_metadata.csv not loaded successfully

**Comment by bcorrie** [comment]
Hi @Hgracia - would you be able to let me know which version of the iReceptor Turnkey you are using?

The AIRR Standard has added some fields in their recent release, and our test data set is a bit behind the current state of the art AIRR Standard. `study_contact` is a new field and it is missing in our test data set. We are working on fixing this problem and expect to have a new release out of the iReceptor Turnkey in the next couple of weeks. If you are just starting to experiment with the software, you might want to hold off for a couple of weeks and use the new release which solve this problem

In the meantime you can simply add an empty column in the test data set with the column header being `study_contact`.

The data loader forces AIRR fields to exist in the data file, but most can be empty if need be.

**Comment by Hgracia** [comment]
I am using version 4.

Adding the column to metadata solved the issue, but then appear another missing column collection_time_point_relative_unit.

I know that i can repeat the process. I only inform you because maybe it is better to update the test data.

Thank you

**Comment by bcorrie** [comment]
Yes, we intend on having a new test data set in a couple of weeks. 

I would anticipate the following fields requiring updates, depending on when you checked out/updated the Turnkey v4.

- study_contact
- collection_time_point_relative_unit
- collection_time_point_relative_unit_id
- template_amount_unit
- template_amount_unit_id
- index_filename
- index_length
- germline_set_ref

These are documented in the AIRR Standard here:

https://docs.airr-community.org/en/stable/datarep/metadata.html

and the release notes for the AIRR v1.4 release is here:

https://docs.airr-community.org/en/stable/news.html
