### ISSUE TITLE
certificate failure with firefox on the gateway

### ISSUE THREAD

**Issue by aurelBZH** [sfu-ireceptor/turnkey-service-php#4]
Hi,
I add the issue here because the issue are closed on the gateway repository. I tried to connect to the gateway today and with firefox and i have a certification error showed in the image under 
[https://framadrop.org/r/iklIvlQmCz#9gV69oqhUr1VEhreZM1Bna/CrZwiAEiMH7JlLw/vtFs=](url) and i had to add a security exception while with chromium the connection work perfectly.
this stackoverflow  post seem to suggest that firefox haven't the same method to detect certification.
https://stackoverflow.com/questions/33401027/firefox-certificate-is-not-trusted-because-the-issuer-certificate-is-unknown

thanks 
Aurélien

**Comment by jeromejaglale** [comment]
Hi Aurélien,

> I add the issue here because the issue are closed on the gateway repository. 

Fixed

>  tried to connect to the gateway today and with firefox and i have a certification error
I also use Firefox (on Linux) and I don't have that problem. 

Are you are using https://gateway.ireceptor.org ?
Are you using Windows?
Are you using Bitdefender? I found this:
https://support.mozilla.org/en-US/kb/error-codes-secure-websites?redirectlocale=en-US&redirectslug=troubleshoot-SEC_ERROR_UNKNOWN_ISSUER#w_bitdefender
and this (see "chosen solution"):
https://support.mozilla.org/en-US/questions/1238264

> while with chromium the connection work perfectly.

Good to know, thank you.

**Comment by aurelBZH** [comment]
i'm on linux with firefox and i'think it's an error linked to firefox. but it's working now ! so i close the issue
