### ISSUE TITLE
launch at boot

### ISSUE THREAD

**Issue by aurelBZH** [sfu-ireceptor/turnkey-service-php#7]
On my system the launch at boot part don't work and the /etc/rc.local is empty. so I create a service script for ireceptor do you want me to create a pull request for it ?

**Comment by jeromejaglale** [comment]
[install_turnkey.sh](https://github.com/sfu-ireceptor/turnkey-service-php/blob/master/scripts/install_turnkey.sh) should have written to /etc/rc.local. Did you get an error message about that when doing the installation?

**Comment by aurelBZH** [comment]
no i  think not and /etc/rc.local is empty. i had seen there is a process for starting at boot before writing a system script. we just had server crash and i was wondering why it didn't restart at server restart.

**Comment by jeromejaglale** [comment]
Ok, thank you.
Which Linux distribution are you using? (we tested it mostly on Ubuntu 16.04)
Could you create that pull request? So it will be there in case we run into that problem again.. Thank you!

**Comment by jeromejaglale** [comment]
I apologize, that modification hasn't been merged into the production branch yet. It will be soon. Sorry for the confusion.
